// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ksi_entertainment/live_record/v1/live_record_service.proto

package live_recordv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/kodmm/ksi-entertainment-proto/go/ksi_entertainment/live_record/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// LiveRecordServiceName is the fully-qualified name of the LiveRecordService service.
	LiveRecordServiceName = "ksi_entertainment.live_record.v1.LiveRecordService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LiveRecordServiceCreateLiveRecordProcedure is the fully-qualified name of the LiveRecordService's
	// CreateLiveRecord RPC.
	LiveRecordServiceCreateLiveRecordProcedure = "/ksi_entertainment.live_record.v1.LiveRecordService/CreateLiveRecord"
	// LiveRecordServiceGetLiveRecordProcedure is the fully-qualified name of the LiveRecordService's
	// GetLiveRecord RPC.
	LiveRecordServiceGetLiveRecordProcedure = "/ksi_entertainment.live_record.v1.LiveRecordService/GetLiveRecord"
	// LiveRecordServiceListLiveRecordsProcedure is the fully-qualified name of the LiveRecordService's
	// ListLiveRecords RPC.
	LiveRecordServiceListLiveRecordsProcedure = "/ksi_entertainment.live_record.v1.LiveRecordService/ListLiveRecords"
	// LiveRecordServiceUpdateLiveRecordProcedure is the fully-qualified name of the LiveRecordService's
	// UpdateLiveRecord RPC.
	LiveRecordServiceUpdateLiveRecordProcedure = "/ksi_entertainment.live_record.v1.LiveRecordService/UpdateLiveRecord"
	// LiveRecordServiceDeleteLiveRecordProcedure is the fully-qualified name of the LiveRecordService's
	// DeleteLiveRecord RPC.
	LiveRecordServiceDeleteLiveRecordProcedure = "/ksi_entertainment.live_record.v1.LiveRecordService/DeleteLiveRecord"
)

// LiveRecordServiceClient is a client for the ksi_entertainment.live_record.v1.LiveRecordService
// service.
type LiveRecordServiceClient interface {
	CreateLiveRecord(context.Context, *connect_go.Request[v1.CreateLiveRecordRequest]) (*connect_go.Response[v1.CreateLiveRecordResponse], error)
	GetLiveRecord(context.Context, *connect_go.Request[v1.GetLiveRecordRequest]) (*connect_go.Response[v1.GetLiveRecordResponse], error)
	ListLiveRecords(context.Context, *connect_go.Request[v1.ListLiveRecordsRequest]) (*connect_go.Response[v1.ListLiveRecordsResponse], error)
	UpdateLiveRecord(context.Context, *connect_go.Request[v1.UpdateLiveRecordRequest]) (*connect_go.Response[v1.UpdateLiveRecordResponse], error)
	DeleteLiveRecord(context.Context, *connect_go.Request[v1.DeleteLiveRecordRequest]) (*connect_go.Response[v1.DeleteLiveRecordResponse], error)
}

// NewLiveRecordServiceClient constructs a client for the
// ksi_entertainment.live_record.v1.LiveRecordService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLiveRecordServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) LiveRecordServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &liveRecordServiceClient{
		createLiveRecord: connect_go.NewClient[v1.CreateLiveRecordRequest, v1.CreateLiveRecordResponse](
			httpClient,
			baseURL+LiveRecordServiceCreateLiveRecordProcedure,
			opts...,
		),
		getLiveRecord: connect_go.NewClient[v1.GetLiveRecordRequest, v1.GetLiveRecordResponse](
			httpClient,
			baseURL+LiveRecordServiceGetLiveRecordProcedure,
			opts...,
		),
		listLiveRecords: connect_go.NewClient[v1.ListLiveRecordsRequest, v1.ListLiveRecordsResponse](
			httpClient,
			baseURL+LiveRecordServiceListLiveRecordsProcedure,
			opts...,
		),
		updateLiveRecord: connect_go.NewClient[v1.UpdateLiveRecordRequest, v1.UpdateLiveRecordResponse](
			httpClient,
			baseURL+LiveRecordServiceUpdateLiveRecordProcedure,
			opts...,
		),
		deleteLiveRecord: connect_go.NewClient[v1.DeleteLiveRecordRequest, v1.DeleteLiveRecordResponse](
			httpClient,
			baseURL+LiveRecordServiceDeleteLiveRecordProcedure,
			opts...,
		),
	}
}

// liveRecordServiceClient implements LiveRecordServiceClient.
type liveRecordServiceClient struct {
	createLiveRecord *connect_go.Client[v1.CreateLiveRecordRequest, v1.CreateLiveRecordResponse]
	getLiveRecord    *connect_go.Client[v1.GetLiveRecordRequest, v1.GetLiveRecordResponse]
	listLiveRecords  *connect_go.Client[v1.ListLiveRecordsRequest, v1.ListLiveRecordsResponse]
	updateLiveRecord *connect_go.Client[v1.UpdateLiveRecordRequest, v1.UpdateLiveRecordResponse]
	deleteLiveRecord *connect_go.Client[v1.DeleteLiveRecordRequest, v1.DeleteLiveRecordResponse]
}

// CreateLiveRecord calls ksi_entertainment.live_record.v1.LiveRecordService.CreateLiveRecord.
func (c *liveRecordServiceClient) CreateLiveRecord(ctx context.Context, req *connect_go.Request[v1.CreateLiveRecordRequest]) (*connect_go.Response[v1.CreateLiveRecordResponse], error) {
	return c.createLiveRecord.CallUnary(ctx, req)
}

// GetLiveRecord calls ksi_entertainment.live_record.v1.LiveRecordService.GetLiveRecord.
func (c *liveRecordServiceClient) GetLiveRecord(ctx context.Context, req *connect_go.Request[v1.GetLiveRecordRequest]) (*connect_go.Response[v1.GetLiveRecordResponse], error) {
	return c.getLiveRecord.CallUnary(ctx, req)
}

// ListLiveRecords calls ksi_entertainment.live_record.v1.LiveRecordService.ListLiveRecords.
func (c *liveRecordServiceClient) ListLiveRecords(ctx context.Context, req *connect_go.Request[v1.ListLiveRecordsRequest]) (*connect_go.Response[v1.ListLiveRecordsResponse], error) {
	return c.listLiveRecords.CallUnary(ctx, req)
}

// UpdateLiveRecord calls ksi_entertainment.live_record.v1.LiveRecordService.UpdateLiveRecord.
func (c *liveRecordServiceClient) UpdateLiveRecord(ctx context.Context, req *connect_go.Request[v1.UpdateLiveRecordRequest]) (*connect_go.Response[v1.UpdateLiveRecordResponse], error) {
	return c.updateLiveRecord.CallUnary(ctx, req)
}

// DeleteLiveRecord calls ksi_entertainment.live_record.v1.LiveRecordService.DeleteLiveRecord.
func (c *liveRecordServiceClient) DeleteLiveRecord(ctx context.Context, req *connect_go.Request[v1.DeleteLiveRecordRequest]) (*connect_go.Response[v1.DeleteLiveRecordResponse], error) {
	return c.deleteLiveRecord.CallUnary(ctx, req)
}

// LiveRecordServiceHandler is an implementation of the
// ksi_entertainment.live_record.v1.LiveRecordService service.
type LiveRecordServiceHandler interface {
	CreateLiveRecord(context.Context, *connect_go.Request[v1.CreateLiveRecordRequest]) (*connect_go.Response[v1.CreateLiveRecordResponse], error)
	GetLiveRecord(context.Context, *connect_go.Request[v1.GetLiveRecordRequest]) (*connect_go.Response[v1.GetLiveRecordResponse], error)
	ListLiveRecords(context.Context, *connect_go.Request[v1.ListLiveRecordsRequest]) (*connect_go.Response[v1.ListLiveRecordsResponse], error)
	UpdateLiveRecord(context.Context, *connect_go.Request[v1.UpdateLiveRecordRequest]) (*connect_go.Response[v1.UpdateLiveRecordResponse], error)
	DeleteLiveRecord(context.Context, *connect_go.Request[v1.DeleteLiveRecordRequest]) (*connect_go.Response[v1.DeleteLiveRecordResponse], error)
}

// NewLiveRecordServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLiveRecordServiceHandler(svc LiveRecordServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	liveRecordServiceCreateLiveRecordHandler := connect_go.NewUnaryHandler(
		LiveRecordServiceCreateLiveRecordProcedure,
		svc.CreateLiveRecord,
		opts...,
	)
	liveRecordServiceGetLiveRecordHandler := connect_go.NewUnaryHandler(
		LiveRecordServiceGetLiveRecordProcedure,
		svc.GetLiveRecord,
		opts...,
	)
	liveRecordServiceListLiveRecordsHandler := connect_go.NewUnaryHandler(
		LiveRecordServiceListLiveRecordsProcedure,
		svc.ListLiveRecords,
		opts...,
	)
	liveRecordServiceUpdateLiveRecordHandler := connect_go.NewUnaryHandler(
		LiveRecordServiceUpdateLiveRecordProcedure,
		svc.UpdateLiveRecord,
		opts...,
	)
	liveRecordServiceDeleteLiveRecordHandler := connect_go.NewUnaryHandler(
		LiveRecordServiceDeleteLiveRecordProcedure,
		svc.DeleteLiveRecord,
		opts...,
	)
	return "/ksi_entertainment.live_record.v1.LiveRecordService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LiveRecordServiceCreateLiveRecordProcedure:
			liveRecordServiceCreateLiveRecordHandler.ServeHTTP(w, r)
		case LiveRecordServiceGetLiveRecordProcedure:
			liveRecordServiceGetLiveRecordHandler.ServeHTTP(w, r)
		case LiveRecordServiceListLiveRecordsProcedure:
			liveRecordServiceListLiveRecordsHandler.ServeHTTP(w, r)
		case LiveRecordServiceUpdateLiveRecordProcedure:
			liveRecordServiceUpdateLiveRecordHandler.ServeHTTP(w, r)
		case LiveRecordServiceDeleteLiveRecordProcedure:
			liveRecordServiceDeleteLiveRecordHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLiveRecordServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLiveRecordServiceHandler struct{}

func (UnimplementedLiveRecordServiceHandler) CreateLiveRecord(context.Context, *connect_go.Request[v1.CreateLiveRecordRequest]) (*connect_go.Response[v1.CreateLiveRecordResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ksi_entertainment.live_record.v1.LiveRecordService.CreateLiveRecord is not implemented"))
}

func (UnimplementedLiveRecordServiceHandler) GetLiveRecord(context.Context, *connect_go.Request[v1.GetLiveRecordRequest]) (*connect_go.Response[v1.GetLiveRecordResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ksi_entertainment.live_record.v1.LiveRecordService.GetLiveRecord is not implemented"))
}

func (UnimplementedLiveRecordServiceHandler) ListLiveRecords(context.Context, *connect_go.Request[v1.ListLiveRecordsRequest]) (*connect_go.Response[v1.ListLiveRecordsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ksi_entertainment.live_record.v1.LiveRecordService.ListLiveRecords is not implemented"))
}

func (UnimplementedLiveRecordServiceHandler) UpdateLiveRecord(context.Context, *connect_go.Request[v1.UpdateLiveRecordRequest]) (*connect_go.Response[v1.UpdateLiveRecordResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ksi_entertainment.live_record.v1.LiveRecordService.UpdateLiveRecord is not implemented"))
}

func (UnimplementedLiveRecordServiceHandler) DeleteLiveRecord(context.Context, *connect_go.Request[v1.DeleteLiveRecordRequest]) (*connect_go.Response[v1.DeleteLiveRecordResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ksi_entertainment.live_record.v1.LiveRecordService.DeleteLiveRecord is not implemented"))
}
