// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: ksi_entertainment/matching/v1/matching_service.proto

package matchingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchingCandidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArtistName string `protobuf:"bytes,2,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
}

func (x *MatchingCandidate) Reset() {
	*x = MatchingCandidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchingCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingCandidate) ProtoMessage() {}

func (x *MatchingCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingCandidate.ProtoReflect.Descriptor instead.
func (*MatchingCandidate) Descriptor() ([]byte, []int) {
	return file_ksi_entertainment_matching_v1_matching_service_proto_rawDescGZIP(), []int{0}
}

func (x *MatchingCandidate) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MatchingCandidate) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

type ListMatchingCandidatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ListMatchingCandidatesRequest) Reset() {
	*x = ListMatchingCandidatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMatchingCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchingCandidatesRequest) ProtoMessage() {}

func (x *ListMatchingCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchingCandidatesRequest.ProtoReflect.Descriptor instead.
func (*ListMatchingCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_ksi_entertainment_matching_v1_matching_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListMatchingCandidatesRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListMatchingCandidatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidates []*MatchingCandidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
}

func (x *ListMatchingCandidatesResponse) Reset() {
	*x = ListMatchingCandidatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMatchingCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchingCandidatesResponse) ProtoMessage() {}

func (x *ListMatchingCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchingCandidatesResponse.ProtoReflect.Descriptor instead.
func (*ListMatchingCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_ksi_entertainment_matching_v1_matching_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListMatchingCandidatesResponse) GetCandidates() []*MatchingCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SendMatchingRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId uint32 `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
}

func (x *SendMatchingRequestRequest) Reset() {
	*x = SendMatchingRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMatchingRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMatchingRequestRequest) ProtoMessage() {}

func (x *SendMatchingRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMatchingRequestRequest.ProtoReflect.Descriptor instead.
func (*SendMatchingRequestRequest) Descriptor() ([]byte, []int) {
	return file_ksi_entertainment_matching_v1_matching_service_proto_rawDescGZIP(), []int{3}
}

func (x *SendMatchingRequestRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendMatchingRequestRequest) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type SendMatchingRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SendMatchingRequestResponse) Reset() {
	*x = SendMatchingRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMatchingRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMatchingRequestResponse) ProtoMessage() {}

func (x *SendMatchingRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMatchingRequestResponse.ProtoReflect.Descriptor instead.
func (*SendMatchingRequestResponse) Descriptor() ([]byte, []int) {
	return file_ksi_entertainment_matching_v1_matching_service_proto_rawDescGZIP(), []int{4}
}

func (x *SendMatchingRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_ksi_entertainment_matching_v1_matching_service_proto protoreflect.FileDescriptor

var file_ksi_entertainment_matching_v1_matching_service_proto_rawDesc = []byte{
	0x0a, 0x34, 0x6b, 0x73, 0x69, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x6b, 0x73, 0x69, 0x5f, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x74, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x22, 0x4d, 0x0a, 0x11, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x72,
	0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6b, 0x73, 0x69, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x74, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x22, 0x5b, 0x0a, 0x1a, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x37, 0x0a, 0x1b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xbc, 0x02, 0x0a, 0x0f, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x97, 0x01, 0x0a,
	0x16, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x3c, 0x2e, 0x6b, 0x73, 0x69, 0x5f, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3d, 0x2e, 0x6b, 0x73, 0x69, 0x5f, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x74, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x8e, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39,
	0x2e, 0x6b, 0x73, 0x69, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x6b, 0x73, 0x69, 0x5f,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x56, 0x5a, 0x54, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x64, 0x6d, 0x6d, 0x2f, 0x6b, 0x73, 0x69, 0x2d,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x6b, 0x73, 0x69, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x74, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ksi_entertainment_matching_v1_matching_service_proto_rawDescOnce sync.Once
	file_ksi_entertainment_matching_v1_matching_service_proto_rawDescData = file_ksi_entertainment_matching_v1_matching_service_proto_rawDesc
)

func file_ksi_entertainment_matching_v1_matching_service_proto_rawDescGZIP() []byte {
	file_ksi_entertainment_matching_v1_matching_service_proto_rawDescOnce.Do(func() {
		file_ksi_entertainment_matching_v1_matching_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_ksi_entertainment_matching_v1_matching_service_proto_rawDescData)
	})
	return file_ksi_entertainment_matching_v1_matching_service_proto_rawDescData
}

var file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ksi_entertainment_matching_v1_matching_service_proto_goTypes = []interface{}{
	(*MatchingCandidate)(nil),              // 0: ksi_entertainment.matching.v1.MatchingCandidate
	(*ListMatchingCandidatesRequest)(nil),  // 1: ksi_entertainment.matching.v1.ListMatchingCandidatesRequest
	(*ListMatchingCandidatesResponse)(nil), // 2: ksi_entertainment.matching.v1.ListMatchingCandidatesResponse
	(*SendMatchingRequestRequest)(nil),     // 3: ksi_entertainment.matching.v1.SendMatchingRequestRequest
	(*SendMatchingRequestResponse)(nil),    // 4: ksi_entertainment.matching.v1.SendMatchingRequestResponse
}
var file_ksi_entertainment_matching_v1_matching_service_proto_depIdxs = []int32{
	0, // 0: ksi_entertainment.matching.v1.ListMatchingCandidatesResponse.candidates:type_name -> ksi_entertainment.matching.v1.MatchingCandidate
	1, // 1: ksi_entertainment.matching.v1.MatchingService.ListMatchingCandidates:input_type -> ksi_entertainment.matching.v1.ListMatchingCandidatesRequest
	3, // 2: ksi_entertainment.matching.v1.MatchingService.SendMatchingRequest:input_type -> ksi_entertainment.matching.v1.SendMatchingRequestRequest
	2, // 3: ksi_entertainment.matching.v1.MatchingService.ListMatchingCandidates:output_type -> ksi_entertainment.matching.v1.ListMatchingCandidatesResponse
	4, // 4: ksi_entertainment.matching.v1.MatchingService.SendMatchingRequest:output_type -> ksi_entertainment.matching.v1.SendMatchingRequestResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ksi_entertainment_matching_v1_matching_service_proto_init() }
func file_ksi_entertainment_matching_v1_matching_service_proto_init() {
	if File_ksi_entertainment_matching_v1_matching_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchingCandidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMatchingCandidatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMatchingCandidatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMatchingRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMatchingRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ksi_entertainment_matching_v1_matching_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ksi_entertainment_matching_v1_matching_service_proto_goTypes,
		DependencyIndexes: file_ksi_entertainment_matching_v1_matching_service_proto_depIdxs,
		MessageInfos:      file_ksi_entertainment_matching_v1_matching_service_proto_msgTypes,
	}.Build()
	File_ksi_entertainment_matching_v1_matching_service_proto = out.File
	file_ksi_entertainment_matching_v1_matching_service_proto_rawDesc = nil
	file_ksi_entertainment_matching_v1_matching_service_proto_goTypes = nil
	file_ksi_entertainment_matching_v1_matching_service_proto_depIdxs = nil
}
